/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package file_choose;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

import javax.swing.JFileChooser;

/**
 *
 * @author doanxuanquyet
 */
public class FrmChooserFile extends javax.swing.JFrame {
    private final int FILE_OPEN = 1;
    private final int FILE_SAVE = 2;

    /**
     * Creates new form FrmChooserFile
     */
    public FrmChooserFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTxArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxArea.setColumns(20);
        jTxArea.setLineWrap(true);
        jTxArea.setRows(5);
        jTxArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTxArea);

        jMenu1.setText("File");

        jMenuItem1.setText("new");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jTxArea.setText("");
        jTxArea.requestFocus();
        JOptionPane.showMessageDialog(null,"new is updating");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        openrateFile("open a file",FILE_OPEN);
        //JOptionPane.showMessageDialog(null,"open is updating");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        openrateFile("save a file",FILE_SAVE);
        //JOptionPane.showMessageDialog(null,"save is updating");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(null,"exit is updating");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    //viet ham tao cua so chon file
    private void openrateFile(String tittle,int type){
        JFileChooser chooser = new JFileChooser(); //tao doi tuong kieu file
        int choose = -1; //tao tham so tra ve
        chooser.setDialogTitle(tittle);
        switch(type){
            case FILE_OPEN:            
                //mo 1 cua so co title la gia tri da duoc setDialogTitle
                choose = chooser.showOpenDialog(null);
                break;
            case FILE_SAVE:
                choose = chooser.showSaveDialog(null);
                break;
        }
        
        if(choose == JFileChooser.APPROVE_OPTION){ //APPROVE_OPTION la gia tri tra ve khi chon file
            File file = chooser.getSelectedFile(); //tao doi tuog file co gia tri khoi tao la file da duoc chon
           
            switch(type){
                case FILE_OPEN: 
                    JOptionPane.showMessageDialog(null,"read a file");
                    readFile(file);
                    break;
                case FILE_SAVE:
                    JOptionPane.showMessageDialog(null,"save a file");
                    writeFile(file);
                    break;
            }
        }
    }
    //viet ham doc file
    private void readFile(File file){
          try{
            jTxArea.setText(""); //dat gia tri rong cho text area
            FileReader fr = new FileReader(file);       //tao doi tuong file reader
            BufferedReader br = new BufferedReader(fr); // tao doi tuong luu file reader
            String line; //tao chuoi de luu du lieu read
            while((line = br.readLine()) != null){
                jTxArea.append(line + "\n");
            }
            br.close();
            fr.close();      
        }catch(IOException e){
            JOptionPane.showMessageDialog(null,"Error to open file: " + e.toString(),"Error",JOptionPane.ERROR_MESSAGE);
        }      
    }
    //viet ham ghi file
    private void writeFile(File file){
        try {
            file.createNewFile(); //lam moi file
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            String data = jTxArea.getText();
            bw.write(data);
            bw.close();
            fw.close();
            readFile(file);
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,"Error to open file: " + e.toString(),"Error",JOptionPane.ERROR_MESSAGE);
        }
            
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChooserFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChooserFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChooserFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChooserFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChooserFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxArea;
    // End of variables declaration//GEN-END:variables
}
