/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sp01;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author doanxuanquyet
 */
    public class FrmGakuseisyokai extends javax.swing.JFrame {
    private final String ADDRESS = "/Users/doanxuanquyet/Desktop/wpro->Java/lesson 4/Seiseki.txt";
    private final File file = new File(ADDRESS);
    private DefaultListModel listModel = null;
    
    /**
     * Creates new form FrmGakuseisyokai
     */
    public FrmGakuseisyokai() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStudentNo = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAdd = new javax.swing.JButton();
        txtUpdate = new javax.swing.JButton();
        txtDelete = new javax.swing.JButton();
        txtOutput = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstData = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("成績データ管理");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("学籍番号");

        jLabel2.setText("氏名");

        jLabel3.setText("得点");

        txtAdd.setText("追加");
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });

        txtUpdate.setText("変更");
        txtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateActionPerformed(evt);
            }
        });

        txtDelete.setText("削除");
        txtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteActionPerformed(evt);
            }
        });

        txtOutput.setText("出力");
        txtOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutputActionPerformed(evt);
            }
        });

        lstData.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDataValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(txtStudentNo))))
                        .addGap(270, 270, 270))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAdd)
                                .addGap(49, 49, 49)
                                .addComponent(txtUpdate)
                                .addGap(69, 69, 69)
                                .addComponent(txtDelete)
                                .addGap(71, 71, 71)
                                .addComponent(txtOutput))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdd)
                    .addComponent(txtUpdate)
                    .addComponent(txtDelete)
                    .addComponent(txtOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        //tao ket noi voi file 
        try {
            try (FileReader fr = new FileReader(file); 
                 BufferedReader br = new BufferedReader(fr)) {
                
                //lay du lieu va truyen vao list
                String line;
                listModel  = new DefaultListModel();
                lstData.setModel(listModel);
                while((line = br.readLine()) != null){
                    listModel.addElement(line);
                }
                br.close();
                fr.close();
                
            }
            
             
        } catch (IOException ex) {
                 Logger.getLogger(FrmGakuseisyokai.class.getName()).log(Level.SEVERE, null, ex);
             }
            
         
    }//GEN-LAST:event_formWindowActivated

    private void lstDataValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDataValueChanged
        // TODO add your handling code here:
        String line;
        
      try{  
        line = lstData.getSelectedValue();
        String[] filed = line.split(",");
        txtStudentNo.setText(filed[0]);
        txtName.setText(filed[1]);
        txtScore.setText(filed[2]);
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_lstDataValueChanged

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
        try{
            String line = "";
        
        line += (txtStudentNo.getText() + ",");
        line += (txtName.getText() + ",");
        line += txtScore.getText();
        
        listModel.addElement(line);
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_txtAddActionPerformed

    private void txtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateActionPerformed
        // TODO add your handling code here:
     
        int x = lstData.getSelectedIndex();
        if(x != -1){
        //lstData.remove(x);
        String line = "";
        line += (txtStudentNo.getText() + ",");
        line += (txtName.getText() + ",");
        line += txtScore.getText();

        listModel.setElementAt(line, x);
    }else{
            JOptionPane.showMessageDialog(null, "please! select item");
        }
        
    }//GEN-LAST:event_txtUpdateActionPerformed

    private void txtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteActionPerformed
        // TODO add your handling code here:
        int x = lstData.getSelectedIndex(); 
        if(x != -1){
             //khong duoc xoa truc tiep ma xoa thong qua doi tuong dinh dang
            listModel.removeElementAt(x);
            //lstData.setModel(listModel);
        }
        else{
            JOptionPane.showMessageDialog(null, "please! select item");
        }
    }//GEN-LAST:event_txtDeleteActionPerformed

    private void txtOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutputActionPerformed
        // TODO add your handling code here:
        try {
                FileWriter fw;
                fw = new FileWriter(file);
            try (BufferedWriter bw = new BufferedWriter(fw)) {
                String line;
                
                //chu y loi load i
                for(int i = 0;i < lstData.getModel().getSize();i++){ //lay thong tin cua list thong qua phuong thuc Model()
                    line = lstData.getModel().getElementAt(i);
                    bw.write(line);
                    bw.newLine(); //xuong dong
                    bw.flush(); //khi xuong dong can them de khong loi//lay gia tri thong qua list.getModel()
                }
                JOptionPane.showMessageDialog(null, "update success");
                bw.close();

            }
                fw.close();             
                
               } catch (IOException ex) {
            Logger.getLogger(FrmGakuseisyokai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGakuseisyokai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGakuseisyokai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGakuseisyokai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGakuseisyokai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGakuseisyokai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstData;
    private javax.swing.JButton txtAdd;
    private javax.swing.JButton txtDelete;
    private javax.swing.JTextField txtName;
    private javax.swing.JButton txtOutput;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtStudentNo;
    private javax.swing.JButton txtUpdate;
    // End of variables declaration//GEN-END:variables
}
