/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package example01_05;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author doanxuanquyet
 */
public class FrmQuestionaire extends javax.swing.JFrame {
    private final String Address = "/Users/doanxuanquyet/Desktop/wpro->Java/lesson 5/AddressMini.txt";
    private final String JOB = "/Users/doanxuanquyet/Desktop/wpro->Java/lesson 5/job.txt";
    private final String NEWFILE = "/Users/doanxuanquyet/Desktop/wpro->Java/lesson 5/Question_answer.txt";

    /**
     * Creates new form FrmQuestionaire
     */
    public FrmQuestionaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdoMen = new javax.swing.JRadioButton();
        rdoWoman = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAddress = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        cmbjob = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JButton();
        chkMusic = new javax.swing.JCheckBox();
        chkTravel = new javax.swing.JCheckBox();
        chkShopping = new javax.swing.JCheckBox();
        chkReadBook = new javax.swing.JCheckBox();
        chkSport = new javax.swing.JCheckBox();
        chkMovie = new javax.swing.JCheckBox();
        btnFinish = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("アンケート");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("性別");

        buttonGroup1.add(rdoMen);
        rdoMen.setSelected(true);
        rdoMen.setText("男");

        buttonGroup1.add(rdoWoman);
        rdoWoman.setText("女");

        jLabel2.setText("住所");

        jScrollPane1.setViewportView(lstAddress);

        jLabel3.setText("職業");

        btnOk.setText("登録");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        chkMusic.setText("音楽鑑賞");

        chkTravel.setText("旅行");

        chkShopping.setText("ショッピング");

        chkReadBook.setText("読書");

        chkSport.setText("スポーツ");

        chkMovie.setText("映画鑑賞");

        btnFinish.setText("終了");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        jLabel4.setText("趣味");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rdoMen)
                        .addGap(26, 26, 26)
                        .addComponent(rdoWoman)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMusic)
                            .addComponent(chkTravel)
                            .addComponent(chkReadBook)
                            .addComponent(btnOk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkShopping)
                            .addComponent(chkMovie)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnFinish)
                                .addComponent(chkSport))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(cmbjob, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoMen)
                    .addComponent(rdoWoman)
                    .addComponent(cmbjob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkMovie)
                        .addGap(30, 30, 30)
                        .addComponent(chkShopping)
                        .addGap(35, 35, 35)
                        .addComponent(chkSport)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkMusic)
                                .addGap(30, 30, 30)
                                .addComponent(chkTravel)
                                .addGap(35, 35, 35)
                                .addComponent(chkReadBook))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOk)
                            .addComponent(btnFinish))
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        FrmNaiyokakunin f2 = new FrmNaiyokakunin();
        
        
        if(rdoMen.isSelected()){ //isSelected
            f2.Sex = "男 ";
        }
        else{
            f2.Sex = "女 ";
        }
        
        int x = lstAddress.getSelectedIndex();
        if(x != -1){
             f2.Address = lstAddress.getSelectedValue(); //getSelectedValue   
        }
        else{
            JOptionPane.showMessageDialog(null,"please! select item","Error", JOptionPane.ERROR_MESSAGE);
        }
        int y = cmbjob.getSelectedIndex();
        if(y != -1){
            f2.job = cmbjob.getSelectedItem().toString();  //getSelectedItem().toString()
        }
        else{
            JOptionPane.showMessageDialog(null,"please! select item","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if(chkMusic.isSelected()){
            f2.hobby += " 音楽鑑賞" + "\n" ;  //append viet them vao
        }
        if(chkMovie.isSelected()){
            f2.hobby += " 映画鑑賞" + "\n";
        }
        if(chkTravel.isSelected()){
            f2.hobby+= " 旅行" + "\n";
        }
        if(chkShopping.isSelected()){
            f2.hobby += " ショッピング" + "\n";
        }
        if(chkReadBook.isSelected()){
            f2.hobby += " 読書" + "\n";
        }
        if(chkSport.isSelected()){
            f2.hobby += " スポーツ" + "\n";
        }
        f2.show();
    }//GEN-LAST:event_btnOkActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    try {
    File file = new File(Address);
    File filejob = new File(JOB);
    
    FileReader frjob = new FileReader(filejob);
    FileReader fr = new FileReader(file);
    
    BufferedReader br = new BufferedReader(fr) ;
    BufferedReader brjob = new BufferedReader(frjob);
    
    String line;
    String linejob;
    
    DefaultListModel listModel = new DefaultListModel(); //tao doi tuong dinh dang list
                lstAddress.setModel(listModel); //cai dat dinh dang list cho listAddress
        
            while((line = br.readLine()) != null){
                listModel.addElement(line);   
            }  
    
    DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
                cmbjob.setModel(comboboxModel);
                
                while((linejob = brjob.readLine()) != null){
                  comboboxModel.addElement(linejob);
                    
                }
             } catch (IOException ex) {
            Logger.getLogger(FrmQuestionaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); 
        int ret = JOptionPane.showConfirmDialog(null, "フォームを閉じていいですか？", "確認",JOptionPane.OK_CANCEL_OPTION,
               JOptionPane.QUESTION_MESSAGE);
       //if(ret == JOptionPane.OK_OPTION){
       if(ret == JOptionPane.CANCEL_OPTION){
           //System.exit(0);
           this.setVisible(false);
           new FrmQuestionaire().setVisible(true);
       }
       else{
          // this.setVisible(true); // function stop closing form
         // new  FrmNaiyokakunin().setVisible(true);
         System.exit(0);
       }
    }//GEN-LAST:event_formWindowClosing

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQuestionaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkMovie;
    private javax.swing.JCheckBox chkMusic;
    private javax.swing.JCheckBox chkReadBook;
    private javax.swing.JCheckBox chkShopping;
    private javax.swing.JCheckBox chkSport;
    private javax.swing.JCheckBox chkTravel;
    private javax.swing.JComboBox<String> cmbjob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstAddress;
    private javax.swing.JRadioButton rdoMen;
    private javax.swing.JRadioButton rdoWoman;
    // End of variables declaration//GEN-END:variables
}
