/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kadai02_04;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author doanxuanquyet
 */
public class FrmQuestionaire extends javax.swing.JFrame {
    private final String Address = "/Users/doanxuanquyet/Desktop/wpro->Java/lesson 4/AddressMini.txt";
    private final String JOB = "/Users/doanxuanquyet/Desktop/wpro->Java/lesson 4/job.txt";
    private final String NEWFILE = "/Users/doanxuanquyet/Desktop/wpro->Java/lesson 4/Question_answer.txt";
    
    private void WriterFile(String line,String Wfile) throws IOException{
        File file = new File(Wfile);
        if(!file.exists()){
             file.createNewFile();
        }
        try (FileWriter fw = new FileWriter(file,true); BufferedWriter bw = new BufferedWriter(fw)) {
            
            bw.write(line);
            bw.newLine();
            bw.flush();
            
        }
        
    }

    /**
     * Creates new form FrmQuestionaire
     */
    public FrmQuestionaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdoMen = new javax.swing.JRadioButton();
        rdoWoman = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAddress = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        cmbjob = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        chkTravel = new javax.swing.JCheckBox();
        chkMusic = new javax.swing.JCheckBox();
        chkReadBook = new javax.swing.JCheckBox();
        chkMovie = new javax.swing.JCheckBox();
        chkSport = new javax.swing.JCheckBox();
        chkShopping = new javax.swing.JCheckBox();
        btnOk = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("アンケート集計");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("性別");

        jLabel2.setText("住所");

        buttonGroup1.add(rdoMen);
        rdoMen.setSelected(true);
        rdoMen.setText("男");

        buttonGroup1.add(rdoWoman);
        rdoWoman.setText("女");

        jScrollPane1.setViewportView(lstAddress);

        jLabel3.setText("職業");

        jLabel4.setText("趣味");

        chkTravel.setText("旅行");

        chkMusic.setText("音楽鑑賞");

        chkReadBook.setText("読書");

        chkMovie.setText("映画鑑賞");

        chkSport.setText("スポーツ");

        chkShopping.setText("ショッピング");

        btnOk.setText("登録");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnReset.setText("リセット");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(rdoMen)
                        .addGap(50, 50, 50)
                        .addComponent(rdoWoman))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(cmbjob, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(btnOk))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkMusic)
                                        .addComponent(chkTravel)
                                        .addComponent(chkReadBook))
                                    .addGap(73, 73, 73)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkSport)
                                        .addComponent(chkShopping)
                                        .addComponent(chkMovie)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnReset)
                                    .addGap(22, 22, 22))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoMen)
                    .addComponent(rdoWoman))
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(cmbjob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMusic)
                    .addComponent(chkMovie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTravel)
                    .addComponent(chkShopping))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSport)
                    .addComponent(chkReadBook))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnReset))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    try {
    File file = new File(Address);
    File filejob = new File(JOB);
    
    FileReader frjob = new FileReader(filejob);
    FileReader fr = new FileReader(file);
    
    BufferedReader br = new BufferedReader(fr) ;
    BufferedReader brjob = new BufferedReader(frjob);
    
    String line;
    String linejob;
    
    DefaultListModel listModel = new DefaultListModel(); //tao doi tuong dinh dang list
                lstAddress.setModel(listModel); //cai dat dinh dang list cho listAddress
        
            while((line = br.readLine()) != null){
                listModel.addElement(line);   
            }  
    
    DefaultComboBoxModel comboboxModel = new DefaultComboBoxModel();
                cmbjob.setModel(comboboxModel);
                
                while((linejob = brjob.readLine()) != null){
                  comboboxModel.addElement(linejob);
                    
                }
             } catch (IOException ex) {
            Logger.getLogger(FrmQuestionaire.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        rdoMen.setSelected(true);
        lstAddress.setSelectedIndex(0);
        cmbjob.setSelectedIndex(-1);
        
        chkMusic.setSelected(false);
        chkMovie.setSelected(false);
        chkTravel.setSelected(false);
        chkShopping.setSelected(false);
        chkReadBook.setSelected(false);
        chkSport.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
       String line;
        
        if(rdoMen.isSelected()){ //isSelected
            line = "男 ";
        }
        else{
            line = "女 ";
        }
        int x = lstAddress.getSelectedIndex();
        if(x != -1){
             line += lstAddress.getSelectedValue(); //getSelectedValue   
        }
        else{
            JOptionPane.showMessageDialog(null,"please! select item","Error", JOptionPane.ERROR_MESSAGE);
        }
        int y = cmbjob.getSelectedIndex();
        if(y != -1){
            line += cmbjob.getSelectedItem().toString();  //getSelectedItem().toString()
        }
        else{
            JOptionPane.showMessageDialog(null,"please! select item","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if(chkMusic.isSelected()){
            line += " 音楽鑑賞 :" ;  //append viet them vao
        }
        if(chkMovie.isSelected()){
            line += " 映画鑑賞 :";
        }
        if(chkTravel.isSelected()){
            line += " 旅行 :";
        }
        if(chkShopping.isSelected()){
            line += " ショッピング :";
        }
        if(chkReadBook.isSelected()){
            line += " 読書 :";
        }
        if(chkSport.isSelected()){
            line += " スポーツ :";
        }
        String line2 = line.substring(0,(line.length() - 2));
        
        try {
            WriterFile(line2,NEWFILE);
            JOptionPane.showMessageDialog(null, "Write Success");
        } catch (IOException ex) {
            Logger.getLogger(FrmQuestionaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQuestionaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQuestionaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkMovie;
    private javax.swing.JCheckBox chkMusic;
    private javax.swing.JCheckBox chkReadBook;
    private javax.swing.JCheckBox chkShopping;
    private javax.swing.JCheckBox chkSport;
    private javax.swing.JCheckBox chkTravel;
    private javax.swing.JComboBox<String> cmbjob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstAddress;
    private javax.swing.JRadioButton rdoMen;
    private javax.swing.JRadioButton rdoWoman;
    // End of variables declaration//GEN-END:variables
}
